### PR TITLE
#15,#16 Removing useless buttons, added note and centered components

### PR DESCRIPTION
**Pull request by Gabbell**

### CODE REVIEW

**Comment by mukulikadey** [comment]
@Gabbell It looks good! But when we click on 'Register", the note at the bottom of the screen should specify that they wouldn't be able to synchronize to google calendar, if they don't use their 'gmail account'. Now it currently just says 'any email', so it might confuse the user.

**Comment by j-suguma** [comment]
Okay i added that small change

**Comment by Gabbell** [comment]
How about this:
Note: You will not be able to synchronize with your Google Calendar if you do not use your gmail account.
Both on login and register

**Comment by mukulikadey** [comment]
Yes, better!

**Pull request merged**
